# Generated by Django 4.1.4 on 2023-06-16 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_region_code_alter_comment_pubdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='datefrom',
        ),
        migrations.RemoveField(
            model_name='place',
            name='dateto',
        ),
        migrations.AddField(
            model_name='place',
            name='timefrom',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='timeto',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilizer',
            name='phone',
            field=models.CharField(default='0', max_length=63),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 15, 33, 57, 236618, tzinfo=datetime.timezone.utc)),
        ),
    ]
